In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

El problema esta definido en el txt adjunto (Definicion_Caracteristicas.txt)

#### Conjunto de entrenamiento

In [2]:
train_df = pd.read_csv('train.csv')
train_df

,id,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
0,0,999,D-penicillamine,21532,M,N,N,N,N,2.3,316.0,3.35,172.0,1601.0,179.80,63.0,394.0,9.7,3.0,D
1,1,2574,Placebo,19237,F,N,N,N,N,0.9,364.0,3.54,63.0,1440.0,134.85,88.0,361.0,11.0,3.0,C
2,2,3428,Placebo,13727,F,N,Y,Y,Y,3.3,299.0,3.55,131.0,1029.0,119.35,50.0,199.0,11.7,4.0,D
3,3,2576,Placebo,18460,F,N,N,N,N,0.6,256.0,3.50,58.0,1653.0,71.30,96.0,269.0,10.7,3.0,C
4,4,788,Placebo,16658,F,N,Y,N,N,1.1,346.0,3.65,63.0,1181.0,125.55,96.0,298.0,10.6,4.0,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7900,7900,1166,D-penicillamine,16839,F,N,N,N,N,0.8,309.0,3.56,38.0,1629.0,79.05,224.0,344.0,9.9,2.0,C
7901,7901,1492,Placebo,17031,F,N,Y,N,N,0.9,260.0,3.43,62.0,1440.0,142.00,78.0,277.0,10.0,4.0,C
7902,7902,1576,D-penicillamine,25873,F,N,N,Y,S,2.0,225.0,3.19,51.0,933.0,69.75,62.0,200.0,12.7,2.0,D
7903,7903,3584,D-penicillamine,22960,M,N,Y,N,N,0.7,248.0,2.75,32.0,1003.0,57.35,118.0,221.0,10.6,4.0,D
7904,7904,1978,D-penicillamine,19237,F,N,N,N,N,0.7,256.0,3.23,22.0,645.0,74.40,85.0,336.0,10.3,3.0,C

#### Conjunto de prueba

In [13]:
test_df = pd.read_csv('test.csv')
test_df

,id,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,7905,3839,D-penicillamine,19724,F,N,Y,N,N,1.2,546.0,3.37,65.0,1636.0,151.90,90.0,430.0,10.6,2.0
1,7906,2468,D-penicillamine,14975,F,N,N,N,N,1.1,660.0,4.22,94.0,1257.0,151.90,155.0,227.0,10.0,2.0
2,7907,51,Placebo,13149,F,N,Y,N,Y,2.0,151.0,2.96,46.0,961.0,69.75,101.0,213.0,13.0,4.0
3,7908,2330,D-penicillamine,20510,F,N,N,N,N,0.6,293.0,3.85,40.0,554.0,125.55,56.0,270.0,10.6,2.0
4,7909,1615,D-penicillamine,21904,F,N,Y,N,N,1.4,277.0,2.97,121.0,1110.0,125.00,126.0,221.0,9.8,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5266,13171,2870,Placebo,12279,F,N,N,N,N,1.3,302.0,3.43,75.0,1345.0,145.00,44.0,181.0,10.6,3.0
5267,13172,1770,Placebo,24803,F,N,N,N,N,0.5,219.0,4.09,121.0,663.0,79.05,94.0,311.0,9.7,3.0
5268,13173,3707,D-penicillamine,16990,F,N,Y,N,N,0.8,315.0,4.09,13.0,1637.0,170.50,70.0,426.0,10.9,3.0
5269,13174,1216,Placebo,11773,F,N,N,N,N,0.7,329.0,3.80,52.0,678.0,57.00,126.0,306.0,10.2,1.0
5270,13175,2272,D-penicillamine,21600,F,N,N,N,N,2.0,232.0,3.42,18.0,1636.0,170.50,83.0,213.0,13.6,2.0

#### Ejemplo de envio competicion

In [14]:
submission_df = pd.read_csv('sample_submission.csv')
submission_df

         id  Status_C  Status_CL  Status_D
0      7905  0.628084   0.034788  0.337128
1      7906  0.628084   0.034788  0.337128
2      7907  0.628084   0.034788  0.337128
3      7908  0.628084   0.034788  0.337128
4      7909  0.628084   0.034788  0.337128
...     ...       ...        ...       ...
5266  13171  0.628084   0.034788  0.337128
5267  13172  0.628084   0.034788  0.337128
5268  13173  0.628084   0.034788  0.337128
5269  13174  0.628084   0.034788  0.337128
5270  13175  0.628084   0.034788  0.337128

[5271 rows x 4 columns]

#### Informacion sobre datasets

In [21]:
submission_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5271 entries, 0 to 5270
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         5271 non-null   int64
 1   Status_C   5271 non-null   float64
 2   Status_CL  5271 non-null   float64
 3   Status_D   5271 non-null   float64
dtypes: float64(3), int64(1)
memory usage: 164.8 KB

In [18]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5271 entries, 0 to 5270
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             5271 non-null   int64
 1   N_Days         5271 non-null   int64
 2   Drug           5271 non-null   object
 3   Age            5271 non-null   int64
 4   Sex            5271 non-null   object
 5   Ascites        5271 non-null   object
 6   Hepatomegaly   5271 non-null   object
 7   Spiders        5271 non-null   object
 8   Edema          5271 non-null   object
 9   Bilirubin      5271 non-null   float64
 10  Cholesterol    5271 non-null   float64
 11  Albumin        5271 non-null   float64
 12  Copper         5271 non-null   float64
 13  Alk_Phos       5271 non-null   float64
 14  SGOT           5271 non-null   float64
 15  Tryglicerides  5271 non-null   float64
 16  Platelets      5271 non-null   float64
 17  Prothrombin    5271 non-null   float64
 18  Stage          5271 non-null   float64
dtypes: float64(10), int64(3), object(6)
memory usage: 782.5+ KB

In [15]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7905 entries, 0 to 7904
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             7905 non-null   int64
 1   N_Days         7905 non-null   int64
 2   Drug           7905 non-null   object
 3   Age            7905 non-null   int64
 4   Sex            7905 non-null   object
 5   Ascites        7905 non-null   object
 6   Hepatomegaly   7905 non-null   object
 7   Spiders        7905 non-null   object
 8   Edema          7905 non-null   object
 9   Bilirubin      7905 non-null   float64
 10  Cholesterol    7905 non-null   float64
 11  Albumin        7905 non-null   float64
 12  Copper         7905 non-null   float64
 13  Alk_Phos       7905 non-null   float64
 14  SGOT           7905 non-null   float64
 15  Tryglicerides  7905 non-null   float64
 16  Platelets      7905 non-null   float64
 17  Prothrombin    7905 non-null   float64
 18  Stage          7905 non-null   float64
 19  Status         7905 non-null   object
dtypes: float64(10), int64(3), object(7)
memory usage: 1.2+ MB

#### Revisar dataset de entrenamiento nulos, unicos y duplicados

In [16]:
for i in train_df.columns:
    print(len(train_df[i].isna()))

7905
7905
7905
7905
7905
7905
7905
7905
7905
7905
7905
7905
7905
7905
7905
7905
7905
7905
7905
7905

In [17]:
for i in train_df.columns:
    print(len(train_df[i].unique()))

7905
461
2
391
2
2
2
2
3
111
226
160
171
364
206
154
227
49
4
3

In [20]:
train_df.duplicated().sum()

0

 Una vez que hemos revisado el conjunto general de nuestros datasets de manera rapida, procedemos a crear la baseline.