In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import log_loss

In [2]:
train_df = pd.read_csv('train.csv')
train_df

,id,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
0,0,999,D-penicillamine,21532,M,N,N,N,N,2.3,316.0,3.35,172.0,1601.0,179.80,63.0,394.0,9.7,3.0,D
1,1,2574,Placebo,19237,F,N,N,N,N,0.9,364.0,3.54,63.0,1440.0,134.85,88.0,361.0,11.0,3.0,C
2,2,3428,Placebo,13727,F,N,Y,Y,Y,3.3,299.0,3.55,131.0,1029.0,119.35,50.0,199.0,11.7,4.0,D
3,3,2576,Placebo,18460,F,N,N,N,N,0.6,256.0,3.50,58.0,1653.0,71.30,96.0,269.0,10.7,3.0,C
4,4,788,Placebo,16658,F,N,Y,N,N,1.1,346.0,3.65,63.0,1181.0,125.55,96.0,298.0,10.6,4.0,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7900,7900,1166,D-penicillamine,16839,F,N,N,N,N,0.8,309.0,3.56,38.0,1629.0,79.05,224.0,344.0,9.9,2.0,C
7901,7901,1492,Placebo,17031,F,N,Y,N,N,0.9,260.0,3.43,62.0,1440.0,142.00,78.0,277.0,10.0,4.0,C
7902,7902,1576,D-penicillamine,25873,F,N,N,Y,S,2.0,225.0,3.19,51.0,933.0,69.75,62.0,200.0,12.7,2.0,D
7903,7903,3584,D-penicillamine,22960,M,N,Y,N,N,0.7,248.0,2.75,32.0,1003.0,57.35,118.0,221.0,10.6,4.0,D
7904,7904,1978,D-penicillamine,19237,F,N,N,N,N,0.7,256.0,3.23,22.0,645.0,74.40,85.0,336.0,10.3,3.0,C

In [3]:
test_df = pd.read_csv('test.csv')
test_df

,id,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,7905,3839,D-penicillamine,19724,F,N,Y,N,N,1.2,546.0,3.37,65.0,1636.0,151.90,90.0,430.0,10.6,2.0
1,7906,2468,D-penicillamine,14975,F,N,N,N,N,1.1,660.0,4.22,94.0,1257.0,151.90,155.0,227.0,10.0,2.0
2,7907,51,Placebo,13149,F,N,Y,N,Y,2.0,151.0,2.96,46.0,961.0,69.75,101.0,213.0,13.0,4.0
3,7908,2330,D-penicillamine,20510,F,N,N,N,N,0.6,293.0,3.85,40.0,554.0,125.55,56.0,270.0,10.6,2.0
4,7909,1615,D-penicillamine,21904,F,N,Y,N,N,1.4,277.0,2.97,121.0,1110.0,125.00,126.0,221.0,9.8,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5266,13171,2870,Placebo,12279,F,N,N,N,N,1.3,302.0,3.43,75.0,1345.0,145.00,44.0,181.0,10.6,3.0
5267,13172,1770,Placebo,24803,F,N,N,N,N,0.5,219.0,4.09,121.0,663.0,79.05,94.0,311.0,9.7,3.0
5268,13173,3707,D-penicillamine,16990,F,N,Y,N,N,0.8,315.0,4.09,13.0,1637.0,170.50,70.0,426.0,10.9,3.0
5269,13174,1216,Placebo,11773,F,N,N,N,N,0.7,329.0,3.80,52.0,678.0,57.00,126.0,306.0,10.2,1.0
5270,13175,2272,D-penicillamine,21600,F,N,N,N,N,2.0,232.0,3.42,18.0,1636.0,170.50,83.0,213.0,13.6,2.0

#### Separamos dataset para primer modelo base

In [16]:
X = train_df.iloc[:, 1:-1]
y = train_df.iloc[:, 19]

In [17]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7905 entries, 0 to 7904
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   N_Days         7905 non-null   int64
 1   Drug           7905 non-null   object
 2   Age            7905 non-null   int64
 3   Sex            7905 non-null   object
 4   Ascites        7905 non-null   object
 5   Hepatomegaly   7905 non-null   object
 6   Spiders        7905 non-null   object
 7   Edema          7905 non-null   object
 8   Bilirubin      7905 non-null   float64
 9   Cholesterol    7905 non-null   float64
 10  Albumin        7905 non-null   float64
 11  Copper         7905 non-null   float64
 12  Alk_Phos       7905 non-null   float64
 13  SGOT           7905 non-null   float64
 14  Tryglicerides  7905 non-null   float64
 15  Platelets      7905 non-null   float64
 16  Prothrombin    7905 non-null   float64
 17  Stage          7905 non-null   float64
dtypes: float64(10), int64(2), object(6)
memory usage: 1.1+ MB

In [18]:
y

0       D
1       C
2       D
3       C
4       C
       ..
7900    C
7901    C
7902    D
7903    D
7904    C
Name: Status, Length: 7905, dtype: object

In [38]:
# normalizar
numerical_data= X.select_dtypes(include='number')
columns_names_numerical = numerical_data.columns
scaler = StandardScaler()
scaled_data = scaler.fit_transform(numerical_data)

In [39]:
scaled_data # datos numericos escalados

array([[-0.94242984,  0.85844803, -0.0772374 , ...,  1.47234122,
        -1.18904919, -0.0375219 ],
       [ 0.4970246 ,  0.23476028, -0.44442941, ...,  1.09502608,
         0.47402401, -0.0375219 ],
       [ 1.27752879, -1.26263383,  0.18504261, ..., -0.75724828,
         1.36952496,  1.11660504],
       ...,
       [-0.41508685,  2.03815544, -0.1559214 , ..., -0.74581448,
         2.64881203, -1.19164884],
       [ 1.42010333,  1.24652041, -0.49688541, ..., -0.50570484,
        -0.03769082,  1.11660504],
       [-0.04768324,  0.23476028, -0.49688541, ...,  0.80918127,
        -0.42147694, -0.0375219 ]])

In [46]:
# codificar categoricos
categorical_data = X.select_dtypes(exclude='number')
encoder = OneHotEncoder(handle_unknown='ignore', drop='first', sparse_output=False)
encoded_data = encoder.fit_transform(categorical_data)
columns_names_categorical = encoder.get_feature_names_out(categorical_data.columns)

In [41]:
encoded_data # matriz densa

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 1.],
       ...,
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [47]:
# Transformo a dataframe, para asignar nombre de columna 
X_numerical = pd.DataFrame(scaled_data, columns=columns_names_numerical)
X_categorical = pd.DataFrame(encoded_data, columns=columns_names_categorical)
# concat de ambas tranformaciones
X_original = pd.concat([X_numerical, X_categorical], axis = 1)
X_original

,N_Days,Age,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Drug_Placebo,Sex_M,Ascites_Y,Hepatomegaly_Y,Spiders_Y,Edema_S,Edema_Y
0,-0.942430,0.858448,-0.077237,-0.176908,-0.572940,1.160785,-0.113334,1.336304,-0.996442,1.472341,-1.189049,-0.037522,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.497025,0.234760,-0.444429,0.068784,-0.024043,-0.275420,-0.197909,0.414968,-0.520497,1.095026,0.474024,-0.037522,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.277529,-1.262634,0.185043,-0.263923,0.004846,0.620561,-0.413812,0.097266,-1.243933,-0.757248,1.369525,1.116605,1.0,0.0,0.0,1.0,1.0,0.0,1.0
3,0.498852,0.023603,-0.523113,-0.484022,-0.139601,-0.341301,-0.086017,-0.887610,-0.368194,0.043117,0.090238,-0.037522,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-1.135271,-0.466107,-0.391973,-0.023351,0.293739,-0.275420,-0.333965,0.224347,-0.368194,0.374697,-0.037691,1.116605,1.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7900,-0.789802,-0.416919,-0.470657,-0.212738,0.033735,-0.604825,-0.098625,-0.728759,2.068644,0.900652,-0.933192,-1.191649,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7901,-0.491858,-0.364741,-0.444429,-0.463548,-0.341826,-0.288596,-0.197909,0.561521,-0.710875,0.134588,-0.805263,1.116605,1.0,0.0,0.0,1.0,0.0,0.0,0.0
7902,-0.415087,2.038155,-0.155921,-0.642698,-1.035169,-0.433534,-0.464242,-0.919380,-1.015479,-0.745814,2.648812,-1.191649,0.0,0.0,0.0,0.0,1.0,1.0,0.0
7903,1.420103,1.246520,-0.496885,-0.524971,-2.306298,-0.683882,-0.427470,-1.173542,0.050637,-0.505705,-0.037691,1.116605,0.0,1.0,0.0,1.0,0.0,0.0,0.0
7904,-0.047683,0.234760,-0.496885,-0.484022,-0.919612,-0.815644,-0.615532,-0.824070,-0.577610,0.809181,-0.421477,-0.037522,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [75]:
# validacion y entrenamiento
X_train,X_val,y_train,y_val = train_test_split(X_original, y, test_size=0.2, random_state=0, stratify=y, shuffle=True)

In [76]:
# modelo predictivo base
lg = LogisticRegression(solver='lbfgs', random_state=0, max_iter=100, multi_class='multinomial')
model = lg.fit(X_train, y_train)

In [77]:
# prediccion de probabilidad 
predict_proba = model.predict_proba(X_val)

In [78]:
predict_proba # objetivo de la competicion

array([[0.76149779, 0.08261356, 0.15588865],
       [0.23589473, 0.00519796, 0.75890732],
       [0.59139798, 0.01286502, 0.39573699],
       ...,
       [0.93330424, 0.00608009, 0.06061568],
       [0.8864927 , 0.02379769, 0.08970961],
       [0.91155255, 0.01064816, 0.07779928]])

In [79]:
# Metrica
print(log_loss(y_val, predict_proba))

0.5190429916646793

#### Prediccion con datos de prueba

In [80]:
test_df.head()

,id,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,7905,3839,D-penicillamine,19724,F,N,Y,N,N,1.2,546.0,3.37,65.0,1636.0,151.90,90.0,430.0,10.6,2.0
1,7906,2468,D-penicillamine,14975,F,N,N,N,N,1.1,660.0,4.22,94.0,1257.0,151.90,155.0,227.0,10.0,2.0
2,7907,51,Placebo,13149,F,N,Y,N,Y,2.0,151.0,2.96,46.0,961.0,69.75,101.0,213.0,13.0,4.0
3,7908,2330,D-penicillamine,20510,F,N,N,N,N,0.6,293.0,3.85,40.0,554.0,125.55,56.0,270.0,10.6,2.0
4,7909,1615,D-penicillamine,21904,F,N,Y,N,N,1.4,277.0,2.97,121.0,1110.0,125.00,126.0,221.0,9.8,1.0

In [81]:
id_ = test_df['id']
X_test = test_df.drop('id', axis = 1)

In [82]:
#normalizar
numerical_= X_test.select_dtypes(include='number')
columns_names_n = numerical_.columns
scaler = StandardScaler()
scaled_ = scaler.fit_transform(numerical_)
# codificar categoricos
categorical_ = X_test.select_dtypes(exclude='number')
encoder = OneHotEncoder(handle_unknown='ignore', drop='first', sparse_output=False)
encoded_ = encoder.fit_transform(categorical_)
columns_names_c = encoder.get_feature_names_out(categorical_.columns)

In [83]:
# Transformo a dataframe, para asignar nombre de columna 
X_num = pd.DataFrame(scaled_, columns=columns_names_n)
X_cat = pd.DataFrame(encoded_, columns=columns_names_c)
# concat de ambas tranformaciones
X_test = pd.concat([X_num, X_cat], axis = 1)
X_test

,N_Days,Age,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Drug_Placebo,Sex_M,Ascites_Y,Hepatomegaly_Y,Spiders_Y,Edema_S,Edema_Y
0,1.656608,0.342186,-0.363546,0.965540,-0.473636,-0.254101,-0.090552,0.782524,-0.480744,1.895231,-0.041463,-1.211516,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.395038,-0.983033,-0.389506,1.534346,1.921728,0.119925,-0.286401,0.782524,0.755049,-0.422762,-0.798430,-1.211516,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-1.829045,-1.492582,-0.155863,-1.005321,-1.629046,-0.499153,-0.439359,-0.895372,-0.271610,-0.582624,2.986409,1.125074,1.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.268052,0.561521,-0.519308,-0.296809,0.879041,-0.576538,-0.649677,0.244331,-1.127159,0.068241,-0.041463,-1.211516,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-0.389878,0.950520,-0.311625,-0.376641,-1.600866,0.468156,-0.362363,0.233097,0.203695,-0.491274,-1.050753,-2.379810,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5266,0.764951,-1.735358,-0.337585,-0.251903,-0.304551,-0.125127,-0.240927,0.641593,-1.355306,-0.948022,-0.041463,-0.043221,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5267,-0.247250,1.759492,-0.545268,-0.666034,1.555379,0.468156,-0.593351,-0.705421,-0.404696,0.536407,-1.176914,-0.043221,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5268,1.535144,-0.420743,-0.467387,-0.187039,1.555379,-0.924769,-0.090035,1.162425,-0.860989,1.849556,0.337021,-0.043221,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5269,-0.757031,-1.876558,-0.493347,-0.117186,0.738137,-0.421768,-0.585599,-1.155788,0.203695,0.479314,-0.546108,-2.379810,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5270,0.214682,0.865688,-0.155863,-0.601170,-0.332732,-0.860282,-0.090552,1.162425,-0.613830,-0.582624,3.743376,-1.211516,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [90]:
# Prediccion con datos de prueba
predict_proba_test = model.predict_proba(X_test)

In [91]:
predict_proba_test

array([[0.85033371, 0.01124463, 0.13842166],
       [0.88309184, 0.03646507, 0.08044309],
       [0.0357567 , 0.01802536, 0.94621794],
       ...,
       [0.85102192, 0.01824011, 0.13073797],
       [0.94123222, 0.03642666, 0.02234112],
       [0.3695399 , 0.01161001, 0.61885009]])

In [100]:
# Guardar en listas cada etiqueta con la probabilidad
Status_C = []
Status_CL = []
Status_D = []
for i in range(len(predict_proba_test)):
    Status_C.append(predict_proba_test[i, 0])
    Status_CL.append(predict_proba_test[i, 1])
    Status_D.append(predict_proba_test[i, 2])

In [101]:
# Creamos la submission
submission_test = {'id': id_, 'Status_C':Status_C, 'Status_CL':Status_CL,'Status_D':Status_D}

In [103]:
data = pd.DataFrame(submission_test)
data

         id  Status_C  Status_CL  Status_D
0      7905  0.850334   0.011245  0.138422
1      7906  0.883092   0.036465  0.080443
2      7907  0.035757   0.018025  0.946218
3      7908  0.911687   0.012470  0.075843
4      7909  0.810629   0.018512  0.170859
...     ...       ...        ...       ...
5266  13171  0.867686   0.033916  0.098398
5267  13172  0.919231   0.008291  0.072479
5268  13173  0.851022   0.018240  0.130738
5269  13174  0.941232   0.036427  0.022341
5270  13175  0.369540   0.011610  0.618850

[5271 rows x 4 columns]

In [104]:
#Guardamos
data.to_csv('baseline.csv', index=False)